### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by GermanBluefox** [soef/iobroker.lightify#1]
You have rather many different adapters here.

Do they work? Can I take it to repository?
iobroker.wm-bus
iobroker.cec
iobroker.lightify
ioBroker.koubachi
iobroker.hid
iobroker.tr-064

Thank you,
Bluefox

**Comment by soef** [comment]
Hi, most of this adapters are in an early development state. Koubachi is bought by the Husqvarna Group and will retire. Existing devices will work with this Adapter. All Adapters worked for me, but they are not realy ready for production. I will try to get them ready for public use.

By the way, can you have a look at the pullrequst of the sonos Adapter? Can I do anything to get that changes to the release Version? 
 
Thank you,
soef
