### ISSUE TITLE
roundRGB

### ISSUE THREAD

**Issue by GermanBluefox** [soef/ioBroker.lightify#7]
Where can I find this function:
https://github.com/soef/ioBroker.lightify/blob/master/lightify.js#L81

??

**Comment by soef** [comment]
Hi, the function parseHexColors was taken from wifilight. In that Project is a colors.js under lib. Is now also fix in this Project. 

Since other changes were made some time ago, the new version can only be installed by @dev tag. So "install iobroker.lightify@dev"

greatings.
